#!/usr/bin/env php

<?php

require __DIR__.'/vendor/autoload.php';
$app = require_once __DIR__.'/framework/app.php';

$serveCommand = new Phine\Console\ServeCommand($app);

$app = new Symfony\Component\Console\Application('Phine', '0.0.0');
$app->add($serveCommand);
$app->run();