#!/usr/bin/env php

<?php

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__ . '/vendor/autoload.php';
    $app = require_once __DIR__.'/bootstrap/app.php';
} else {
    require __DIR__.'/../../autoload.php';
    if (file_exists(__DIR__.'/../../../bootstrap/app.php')) {
        $app = require_once __DIR__.'/../../../bootstrap/app.php';
    } else {
        // Use $app from vendor current location for first run (init)
        $app = require_once __DIR__.'/bootstrap/app.php';
    }
}

$serveCommand = new Phine\Console\ServeCommand($app);
$initCommand = new Phine\Console\InitCommand($app);

$app = new Symfony\Component\Console\Application('Phine', '0.0.1');
$app->add($serveCommand);
$app->add($initCommand);
$app->run();